# Generated by Django 5.2.1 on 2025-05-14 17:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=100)),
                ('equipo_local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_local', to='equipos.equipo')),
                ('equipo_visitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_visitante', to='equipos.equipo')),
            ],
        ),
    ]
