# Generated by Django 5.2.1 on 2025-05-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='miembros',
        ),
    ]
